version: "3.7"
services:
  app:
    build: .
    container_name: spring-boot-rest
    image: spring-boot-rest:latest
    environment:
      - MYSQL_HOST=mysql
    ports:
      - 80:8080
    networks:
      - app-network
    volumes:
      - java-data:/app/uploads
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    image: mysql:8.0
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=jobapp
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  java-data:
